### ISSUE TITLE
Data Pipeline Improvements

### ISSUE THREAD

**Issue by stephankokkas** [DataBytes-Organisation/Project-Echo#44]
There are a number of potential improvements to the data pipeline that should be implemented shortly:

1. If at any point the pipeline fails, it will not resume from where it has failed, but instead will clear the directory and restart. This was initially implemented for debugging purposes but is no longer needed. 
2. The speed of the pipeline needs to be improved. Currently, with a dataset of 1,000 audio files, it will take over 1 hour to process (if not longer depending no the specs of your computer) the audio files and preprocess them into tensors. 
3. There are multiple data pipelines - a pipeline for model training, for raw data preprocessing and augmenting, and for raw data predictions in line. All of these pipelines should be consolidated into a single master pipeline.

**Comment by akudilcz** [comment]
This is now done!  See https://github.com/DataBytes-Organisation/Project-Echo/blob/main/src/Components/Engine/generic_engine_pipeline.ipynb
